#!/usr/bin/env zsh
# shellcheck shell=bash

copy () { #: prepare stuff and watch
    rcp ~/Code/symfony/src/Symfony/Component/ExpressionLanguage/* .
}

#
# BOILERPLATE
#
r='./task'
NAME='expression-language-custom'

about () { #: show help & commands
    echo "$NAME script runner"
    echo "Commands:"
    sed -nr 's/^(.*) \(\).* #: (.*)$/  \1\t\2/p' $r | expand -20
	# this sed looks crazy, but it just parses this file
	# and finds lines with `() #: ` and prints them in a nice format
}

if [[ $# -gt 0 ]]; then
	command="$1"
	shift 1
	if type "$command" 2>/dev/null | grep -q 'function'; then
		$command "$@"
	else
		about
		echo "No command '$command'."
	fi;
else
    # task to run by default if no arguments are passed
	about
fi
